-- 0001_init — the initial RentHouse schema.
--
-- UUID keys are generated by gen_random_uuid(), built into PostgreSQL since 13,
-- so no extension is required and rows inserted outside the application still
-- get valid keys.
--
-- Delete behaviour is chosen per relationship rather than cascading everywhere:
--   CASCADE  where the child has no meaning without the parent (a photo without
--            its listing, a favourite of a deleted apartment, a join row).
--   RESTRICT where the parent is reference data that must not disappear while
--            it is still in use (a district with live listings).

CREATE TABLE users (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name    varchar(100) NOT NULL,
    last_name     varchar(100) NOT NULL,
    email         varchar(255) NOT NULL,
    phone         varchar(32)  NOT NULL,
    password_hash varchar(255) NOT NULL,
    avatar_url    text,
    language      varchar(2)   NOT NULL DEFAULT 'uz',
    theme         varchar(5)   NOT NULL DEFAULT 'light',
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uq_users_email  UNIQUE (email),
    CONSTRAINT uq_users_phone  UNIQUE (phone),
    CONSTRAINT ck_users_language CHECK (language IN ('uz', 'ru', 'en')),
    CONSTRAINT ck_users_theme    CHECK (theme    IN ('light', 'dark'))
);

-- UNIQUE already creates a b-tree index, so email and phone are indexed for
-- login lookups without a second index on the same column.

CREATE TABLE districts (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name       varchar(100)     NOT NULL,
    slug       varchar(100)     NOT NULL,
    latitude   double precision NOT NULL,
    longitude  double precision NOT NULL,
    created_at timestamptz      NOT NULL DEFAULT now(),
    updated_at timestamptz      NOT NULL DEFAULT now(),

    CONSTRAINT uq_districts_name UNIQUE (name),
    CONSTRAINT uq_districts_slug UNIQUE (slug),
    CONSTRAINT ck_districts_latitude  CHECK (latitude  BETWEEN -90  AND 90),
    CONSTRAINT ck_districts_longitude CHECK (longitude BETWEEN -180 AND 180)
);

CREATE TABLE amenities (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name       varchar(100) NOT NULL,
    slug       varchar(100) NOT NULL,
    icon       varchar(100),
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uq_amenities_slug UNIQUE (slug)
);

CREATE TABLE apartments (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id      uuid             NOT NULL,
    district_id   uuid             NOT NULL,
    title         varchar(255)     NOT NULL,
    description   text             NOT NULL DEFAULT '',
    price         numeric(14, 2)   NOT NULL,
    currency      varchar(3)       NOT NULL DEFAULT 'UZS',
    rental_period varchar(10)      NOT NULL DEFAULT 'monthly',
    rooms         smallint         NOT NULL,
    area          integer          NOT NULL,
    floor         smallint         NOT NULL,
    total_floors  smallint         NOT NULL,
    furnished     boolean          NOT NULL DEFAULT false,
    status        varchar(10)      NOT NULL DEFAULT 'draft',
    address       varchar(255)     NOT NULL,
    latitude      double precision NOT NULL,
    longitude     double precision NOT NULL,
    views_count   bigint           NOT NULL DEFAULT 0,
    created_at    timestamptz      NOT NULL DEFAULT now(),
    updated_at    timestamptz      NOT NULL DEFAULT now(),

    -- Deleting an account removes the listings it published.
    CONSTRAINT fk_apartments_owner
        FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
    -- A district in use cannot be deleted; its listings would lose their location.
    CONSTRAINT fk_apartments_district
        FOREIGN KEY (district_id) REFERENCES districts (id) ON DELETE RESTRICT,

    CONSTRAINT ck_apartments_currency      CHECK (currency      IN ('UZS', 'USD')),
    CONSTRAINT ck_apartments_rental_period CHECK (rental_period IN ('monthly', 'daily')),
    CONSTRAINT ck_apartments_status        CHECK (status IN ('draft', 'pending', 'active', 'closed')),
    CONSTRAINT ck_apartments_price         CHECK (price > 0),
    CONSTRAINT ck_apartments_rooms         CHECK (rooms > 0),
    CONSTRAINT ck_apartments_area          CHECK (area  > 0),
    CONSTRAINT ck_apartments_floors        CHECK (floor > 0 AND total_floors > 0 AND floor <= total_floors),
    CONSTRAINT ck_apartments_views_count   CHECK (views_count >= 0),
    CONSTRAINT ck_apartments_latitude      CHECK (latitude  BETWEEN -90  AND 90),
    CONSTRAINT ck_apartments_longitude     CHECK (longitude BETWEEN -180 AND 180)
);

CREATE INDEX idx_apartments_owner_id    ON apartments (owner_id);
CREATE INDEX idx_apartments_district_id ON apartments (district_id);
CREATE INDEX idx_apartments_status      ON apartments (status);
CREATE INDEX idx_apartments_price       ON apartments (price);
CREATE INDEX idx_apartments_rooms       ON apartments (rooms);
CREATE INDEX idx_apartments_created_at  ON apartments (created_at DESC);

-- The browse screen is "active listings, newest first"; a composite index means
-- that query never has to filter one column and sort on another separately.
CREATE INDEX idx_apartments_status_created_at ON apartments (status, created_at DESC);

CREATE TABLE apartment_images (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    apartment_id uuid        NOT NULL,
    url          text        NOT NULL,
    is_primary   boolean     NOT NULL DEFAULT false,
    sort_order   smallint    NOT NULL DEFAULT 0,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_apartment_images_apartment
        FOREIGN KEY (apartment_id) REFERENCES apartments (id) ON DELETE CASCADE,
    CONSTRAINT ck_apartment_images_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_apartment_images_apartment_id ON apartment_images (apartment_id);

-- At most one cover photo per apartment. A partial unique index expresses this
-- exactly: it constrains the primary rows and ignores all the others.
CREATE UNIQUE INDEX uq_apartment_images_one_primary
    ON apartment_images (apartment_id) WHERE is_primary;

CREATE TABLE apartment_amenities (
    apartment_id uuid NOT NULL,
    amenity_id   uuid NOT NULL,

    -- The pair is the key, so a duplicate link is impossible by construction.
    CONSTRAINT pk_apartment_amenities PRIMARY KEY (apartment_id, amenity_id),
    CONSTRAINT fk_apartment_amenities_apartment
        FOREIGN KEY (apartment_id) REFERENCES apartments (id) ON DELETE CASCADE,
    CONSTRAINT fk_apartment_amenities_amenity
        FOREIGN KEY (amenity_id) REFERENCES amenities (id) ON DELETE CASCADE
);

-- The primary key already indexes apartment_id (it leads the key); this covers
-- the other direction, "which apartments have Wi-Fi".
CREATE INDEX idx_apartment_amenities_amenity_id ON apartment_amenities (amenity_id);

CREATE TABLE favorites (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      uuid        NOT NULL,
    apartment_id uuid        NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_favorites_user_apartment UNIQUE (user_id, apartment_id),
    CONSTRAINT fk_favorites_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_favorites_apartment
        FOREIGN KEY (apartment_id) REFERENCES apartments (id) ON DELETE CASCADE
);

-- uq_favorites_user_apartment covers user_id lookups (leading column); this
-- covers "how many people saved this listing".
CREATE INDEX idx_favorites_apartment_id ON favorites (apartment_id);

CREATE TABLE conversations (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    apartment_id uuid        NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),

    -- Removing a listing removes the threads about it, rather than leaving
    -- conversations pointing at nothing. See the README note: if chat history
    -- must outlive a listing, this becomes ON DELETE SET NULL with a nullable
    -- apartment_id.
    CONSTRAINT fk_conversations_apartment
        FOREIGN KEY (apartment_id) REFERENCES apartments (id) ON DELETE CASCADE
);

CREATE INDEX idx_conversations_apartment_id ON conversations (apartment_id);

CREATE TABLE conversation_participants (
    conversation_id uuid        NOT NULL,
    user_id         uuid        NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT pk_conversation_participants PRIMARY KEY (conversation_id, user_id),
    CONSTRAINT fk_conversation_participants_conversation
        FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
    CONSTRAINT fk_conversation_participants_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- "Which conversations is this user in" — the primary key leads with
-- conversation_id, so the reverse lookup needs its own index.
CREATE INDEX idx_conversation_participants_user_id ON conversation_participants (user_id);

CREATE TABLE messages (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id uuid        NOT NULL,
    sender_id       uuid        NOT NULL,
    body            text        NOT NULL,
    is_read         boolean     NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_messages_conversation
        FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_sender
        FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_messages_body_not_blank CHECK (btrim(body) <> '')
);

-- Reading a thread is always "this conversation, in time order", so the two
-- columns are indexed together rather than separately.
CREATE INDEX idx_messages_conversation_created ON messages (conversation_id, created_at);
CREATE INDEX idx_messages_sender_id            ON messages (sender_id);
CREATE INDEX idx_messages_created_at           ON messages (created_at DESC);

-- Unread badges count only unread rows, so the index stores only those.
CREATE INDEX idx_messages_unread ON messages (conversation_id) WHERE NOT is_read;
