-- 0005_message_attachments — pictures, documents and voice notes in chat.
--
-- Until now a message was text and only text, which the NOT-blank constraint
-- enforced. An image carries no words, so that constraint has to learn the
-- difference between a message that lost its text and one that never had any.
--
-- Nothing here is destructive: `kind` defaults to 'text', which is what every
-- existing row is.

-- ---------------------------------------------------------------------------
-- messages: what kind of message this is
-- ---------------------------------------------------------------------------

-- A column rather than a lookup at the attachment table, because the check
-- below has to be satisfiable from this row alone — a CHECK cannot query
-- another table.
ALTER TABLE messages
    ADD COLUMN kind varchar(10) NOT NULL DEFAULT 'text';

ALTER TABLE messages
    ADD CONSTRAINT ck_messages_kind
        CHECK (kind IN ('text', 'image', 'file', 'audio'));

-- Text still has to say something; an attachment message may say nothing,
-- because the attachment is the message. A withdrawn message may say nothing
-- either, which 0004 already allowed for.
ALTER TABLE messages DROP CONSTRAINT ck_messages_body_not_blank;
ALTER TABLE messages ADD CONSTRAINT ck_messages_body_not_blank
    CHECK (deleted_at IS NOT NULL OR kind <> 'text' OR btrim(body) <> '');

-- ---------------------------------------------------------------------------
-- message_attachments
-- ---------------------------------------------------------------------------

-- A separate table rather than columns on `messages`: most messages are text
-- and would carry six permanently-NULL columns, and a row here is what a future
-- multi-attachment message needs without another migration.
--
-- The bytes are NOT stored here. A row is a poor filesystem, and it would put
-- image traffic through the connection pool the rest of the application needs.
-- What is stored is where the file went and what it is.
CREATE TABLE message_attachments (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    message_id uuid         NOT NULL,

    -- Which of the three shapes the UI should render. Mirrors messages.kind for
    -- the attachment itself, so a query about attachments need not join back.
    kind varchar(10) NOT NULL,

    -- What the sender called it, shown in the UI. Never used to build a path:
    -- a filename from a client is a path traversal waiting to happen.
    original_name varchar(255) NOT NULL,
    -- What it was actually saved as — random, generated by the storage layer.
    stored_path text NOT NULL,
    -- The URL it is served from. Kept alongside the path so moving to object
    -- storage later changes how this is produced, not what reads it.
    url text NOT NULL,

    mime_type varchar(120) NOT NULL,
    size_bytes bigint NOT NULL,

    -- Set for audio, where the player needs a length before the file loads.
    -- NULL for everything else.
    duration_seconds integer,

    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_message_attachments_message
        FOREIGN KEY (message_id) REFERENCES messages (id) ON DELETE CASCADE,

    CONSTRAINT ck_message_attachments_kind
        CHECK (kind IN ('image', 'file', 'audio')),
    CONSTRAINT ck_message_attachments_size
        CHECK (size_bytes > 0),
    CONSTRAINT ck_message_attachments_duration
        CHECK (duration_seconds IS NULL OR duration_seconds >= 0),
    CONSTRAINT ck_message_attachments_name_not_blank
        CHECK (btrim(original_name) <> '')
);

-- Loading a thread asks for the attachments of a page of messages.
CREATE INDEX idx_message_attachments_message ON message_attachments (message_id);
